title: SunnyZFChen's Homepage
page-top-title: SunnyZFChen
top-section-bg-text: Software Engineering
home-subtitle: SunnyZFChen&ensp;|&ensp;陈志福
copyright-text: '&copy; SunnyZFChen 2026-2026. All Rights Reserved.'
