title: SunnyZFChen's Homepage
page-top-title: SunnyZFChen
top-section-bg-text: Computer Science
home-subtitle: SunnyZFChen&ensp;|&ensp;
copyright-text: '&copy; SunnyZFChen 2026-2026. All Rights Reserved.'
